export const fakeChips = [
    {name:'Чипс 1', value: 'Чипс 1'},
    {name:'Чипс 2', value: 'Чипс 2'},
    {name:'Длинный Чипс 3', value: 'Очень длинный Чипс 3'},
    {name:'Чипс 4', value: 'Чипс 4'},
    {name:'Чипс 5', value: 'Чипс 5'},
    {name:'Чипс 6', value: 'Чипс 6'},
    {name:'Чипс 7', value: 'Чипс 7'},
    {name:'Чипс 8', value: 'Чипс 8'},
    {name:'Чипс 9', value: 'Чипс 9'},
    {name:'Чипс 10', value: 'Чипс 10'},
    {name:'ещё длинный Чипс 11', value: 'один длинный Чипс 11'},
    {name:'Чипс 12', value: 'Чипс 12'},
    {name:'Чипс 13', value: 'Чипс 13'},
    {name:'Чипс 14', value: 'Чипс 14'},
]
